[phases.setup]
  nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
  cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
  ]
  cacheDirectories = ["/root/.cache/pip"]

[start]
  cmd = "gunicorn Sujan.wsgi --bind 0.0.0.0:$PORT