# Generated by Django 5.1.6 on 2025-02-25 06:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_about_content_alter_honor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='English',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='about',
            name='Hindi',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='about',
            name='Nepali',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='about',
            name='Skills',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
