# Generated by Django 5.1.6 on 2025-02-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_english_about_hindi_about_nepali_about_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='tagline',
            field=models.CharField(default='Author, Researcher & Agriculturist', max_length=200),
        ),
    ]
