# Generated by Django 5.1.6 on 2025-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_involved',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization_involved',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/organization/'),
        ),
        migrations.AddField(
            model_name='organization_involved',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization_involved',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
