# Generated by Django 5.1.6 on 2025-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_honor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='created_at',
            field=models.DateField(),
        ),
    ]
